### ISSUE TITLE
Blinking status bar?

### ISSUE THREAD

**Issue by tomas** [adsr/mle#1]
Hi and congrats for your work! I recently discovered mle and I'm loving it so far.

I found out a weird thing with the status bar, though. When I run mle outside of an X session (directly from the system shell) the status bar blinks every 1 second or so, but only when showing the default `[mode] buf/line/col` info. When I hit Ctrl+O and `new_open: File?` is shown, then the blinking stops. But then if I hit Ctrl-C then the other screen is shown and it starts again.

Do you know what might be going on? This doesn't happen when I run mle from within an X session, and I'm not using any VGA/framebuffer kernel modes.

**Comment by adsr** [comment]
Hi, thanks for checking out the editor. You are one of the first people to use it. How did you find it if you don't mind my asking?

I'm not sure about the blinking issue. Is your setup using agetty for virtual terminals? I tested in mine and I don't get that behavior. Does it blink even if you don't input anything? The editor should be blocked indefinitely on `select` until there is some input. If you can confirm that is the case (with strace or similar), maybe something external is causing the blinking.

**Comment by rindeal** [comment]
It happens to me even in xsession as the bug depends on a terminal emulator, I'll submit a PR in a moment.

**Comment by adsr** [comment]
Thanks for the patch @rindeal !

**Comment by tomas** [comment]
Worked nicely, thanks @rindeal.

@adsr I found out about mle from [this page](http://texteditors.org/cgi-bin/wiki.pl?TinyEditors). Do you need help with anything besides testing?

**Comment by adsr** [comment]
@tomas There is a list of todo items, albeit cryptically written, at the bottom of `mle.h`. Patches are of course welcome. Besides that I'm unsure about the whole lel thing. It was fun to write but I'm not convinced it adds real value or if it's mainly bloat.

**Comment by tomas** [comment]
Cool, I'll take a look and see if there's anything I can help with.

What's the lel thing, by the way?

**Comment by adsr** [comment]
It is a tiny text editing language sort of like sam command lang[1]. There are some basic docs under "lel: edit language" in `README.md`. I am unconvinced it is generally useful or that anyone would reach for it as a tool versus simple editing commands.

[1] http://doc.cat-v.org/bell_labs/sam_lang_tutorial/
