### ISSUE TITLE
[Question] why was wren replaced by lua

### ISSUE THREAD

**Issue by velkyel** [adsr/mle#10]
hello,

these days I'm diving into wren and found this project where was wren replaced by lua.  I'm curious, why?  technical issues or something else?
thanks

**Comment by adsr** [comment]
Hello. When I was using Wren, the VM was not re-entrant. So if Wren code invoked a C callback, it could not in turn invoke a Wren callback at that point. Not sure if this is still the case. Otherwise I really enjoyed using it. Highly recommend it.
