### ISSUE TITLE
fails to build on several architectures

### ISSUE THREAD

**Issue by cdluminate** [adsr/mle#16]
https://buildd.debian.org/status/package.php?p=mle

Click `Build-Attempted` to see the full log.

**Comment by adsr** [comment]
Thanks for the report. Is there a way to re-run the tests against a new version? and/or to get a shell on the build hosts?

**Comment by cdluminate** [comment]
The package will be rebuilt every time we upload a new version (or revision). Shell access is not available.

**Comment by adsr** [comment]
OK, I uploaded 1.3-2 on mentors which may fix some stuff (0d51b0d). After that I will need to setup qemu or something to bugfix.

**Comment by cdluminate** [comment]
Does that mean I should check and upload `1.3-2` before you finish debugging with qemu?

**Comment by adsr** [comment]
Only if it's easy for you. If it's non-trivial or time consuming at all, I'll let you know when I've sorted it out on qemu.

**Comment by adsr** [comment]
I fixed a few bugs and have tests passing on arm64, i386, and mips on qemu. I was not able to reproduce some of the functional test failures so I think certain builds will continue to fail. I suspect these may be related to env or terminfo. I'll continue to hunt them down. Also reuploaded 1.3-2 on mentors.

**Comment by cdluminate** [comment]
There must not be any difference between the source code of `1.3-1` and `1.3-2` uploads except for that of the `debian/` directory. (1) If you don't mind tagging `1.3.1`, then we can upload `1.3.1-1.` (2) If you don't plan to bump the version number, you can put the diff (e.g. `diff 1.3 -> head`) to the `debian/patches` directory.

**Comment by adsr** [comment]
Hm, I see the updated code.

```
test@debian:~/tmp$ wget -q https://mentors.debian.net/debian/pool/main/m/mle/mle_1.3.orig.tar.xz # (timestamp 2018-12-28 22:07)
test@debian:~/tmp$ tar xf mle_1.3.orig.tar.xz
test@debian:~/tmp$ grep -r inttypes.h
buffer.c:#include <inttypes.h>
cmd.c:#include <inttypes.h>
tests/unit/test.h:#include <inttypes.h>
uscript.c:#include <inttypes.h>
editor.c:#include <inttypes.h>
```

(`inttypes.h` is part of the recent bugfixes.)

Are we not supposed to replace/reupload `orig.tar.xz` when bumping only the release number?

I reuploaded `1.3-2` with `debian/patches` as per your suggestion (2) (timestamp `2018-12-31 16:11`). If updating `orig.tar.xz` is a mistake in this scenario, let me know and I'll reupload the original `orig.tar.xz` from `1.3-1`.

Thanks for the patience. Still getting the hang of Debian packaging.

**Comment by cdluminate** [comment]
> Are we not supposed to replace/reupload `orig.tar.xz` when bumping only the release number?

The orig.tar.xz file cannot be changed when bumping only the Debian revision number.

> I reuploaded `1.3-2` with `debian/patches` as per your suggestion (2) (timestamp `2018-12-31 16:11`). If updating `orig.tar.xz` is a mistake in this scenario, let me know and I'll reupload the original `orig.tar.xz` from `1.3-1`.

Let me check it later...

**Comment by cdluminate** [comment]
The result looks quite good. https://buildd.debian.org/status/package.php?p=mle

**Comment by adsr** [comment]
Great, thank you.
