### ISSUE TITLE
Possible to highlight current match?

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#19]
When I use `C-f` to search for a given word, I sometimes having a hard time seeing where the cursor is. Highlighting the current match would make that a lot easier.

Is that possible? If not, is there anything I can do to help?

**Comment by adsr** [comment]
There is not a built-in way but you can script it. As a start:

```lua
-- uscript.lua
-- Usage: mle -x uscript.lua

set_anchor = 0
function hook_search_after(ctx)
    mle.cursor_select_by_word(ctx["cursor"], 1)
    set_anchor = 1
end

function hook_search_before(ctx)
    if set_anchor then
        mle.cursor_lift_anchor(ctx["cursor"])
    end
end

mle.editor_register_observer("cmd:cmd_search:after", hook_search_after)
mle.editor_register_observer("cmd:cmd_search_next:after", hook_search_after)
mle.editor_register_observer("cmd:cmd_search:before", hook_search_before)
mle.editor_register_observer("cmd:cmd_search_next:before", hook_search_before)
```

**Comment by KevinSjoberg** [comment]
The `cmd_isearch` behaviour is exactly what I'm after. If you're interested I'd be happy to try my hands at implementing a highlight for the current `fsearch` match myself. I'm currently at chapter 5 in the K.N. King book, but I'll do my best!

**Comment by adsr** [comment]
Glad `cmd_isearch` works for you. Always open to pull requests. Thanks @KevinSjoberg.
