### ISSUE TITLE
Possible to suspend mle?

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#21]
Is it possible to suspend `mle`? In `nano` I can for instance do `C-z` to suspend it temporarily and then do `fg` in my terminal to resume.

**Comment by adsr** [comment]
Not currently but good idea. I will add the feature.

**Comment by KevinSjoberg** [comment]
Sweet, appreciate it! :)

**Comment by adsr** [comment]
Added in a19ea77. Binds to `F4` by default but you can rebind it as usual. Thanks for the feature request @KevinSjoberg.

**Comment by KevinSjoberg** [comment]
Sweet, thank you! Just tried out, works great. :+1:
