### ISSUE TITLE
Avoid `grep -P` in tests

### ISSUE THREAD

**Issue by adsr** [adsr/mle#27]
@KevinSjoberg noted in #26 that the functional test suite does not work on macOS due to the use of `grep -P` which is not present in BSD grep. It is probably easiest to switch these to `grep -E`.

**Comment by adsr** [comment]
@KevinSjoberg or someone else with macOS can you confirm tests are passing?

**Comment by KevinSjoberg** [comment]
I've verified that all tests are passing in latest `master`! 🎉
