### ISSUE TITLE
How do I copy something to the system clipboard

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#28]
For instance, if I copy a line using `M-k`, how do I get the selection into my system clipboard? Right now I'm doing `M-e echo "C-u" | pbcopy`.

**Comment by adsr** [comment]
I added an example Lua script which does this:

https://github.com/adsr/mle/blob/3f3b9175fe3e124d2f06ca9bee2346a8fb7c5758/uscript.lua#L17-L25

(Can replace `xclip` with `pbcopy`.)
