### ISSUE TITLE
Possible to define tab width, tab to space and smart indent per language

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#29]
Is it possible to set the `tab_to_space`, `tab_with` and smart indent on a language basis? For instance, right now, smart indent does not work for Ruby that uses `def`,`do`/`end` instead of `{`/`}`.

**Comment by adsr** [comment]
`tab_to_space` and `tab_width` can be specified as part of a syntax definition via `-S`. Presently auto-indent is a global setting and only works with brackets. It is implemented in the `_cmd_insert_auto_indent*` functions which may be refactorable to support Ruby and Python style indents.
