### ISSUE TITLE
Would you be up for some pair programming?

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#30]
I really enjoy the simplicity of `mle` and would really like to spend more time on it. Perhaps on documentation but also on bug fixes and features. Would you be interested in doing a pairing session where you walk me through the current state of `mle`?

I feel I don't have a good understanding of how the `mlerc` file work, how the extension API work, how custom syntax is defined, and new questions keeping coming up. I know it's a big ask, so I'm totally cool with you saying no. 🙂

**Comment by adsr** [comment]
Very glad to hear that! Feel free to email me and we can find a time.
