### ISSUE TITLE
Shift+tab does not unident

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#33]
I know we can use `M-.` and `M-,` to indent and unident respectively. However, since `tab` can be used to indent, I would expect `Shift-tab` to unident.

Right now, the behaviour I'm seeing when pressing `Shift-tab` is a `Z` being inserted at nearest `{`. Hitting it multiple times will continue walking up the tree, inserting `Z` at every `{` it can find.

The `Z` could potentially be an escape sequence or related key code?

**Comment by adsr** [comment]
https://github.com/adsr/mle/issues/34#issuecomment-627749557

**Comment by adsr** [comment]
Shift-tab can now be bound to keyname `backtab`.
