### ISSUE TITLE
Setting an anchor using BOL/EOL strategy does not work if the line is empty

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#37]
Right now, it's not possible to set an anchor using the BOL (`C-2 a`) and EOL `C-2 e`) strategies. It will simply error with a message like this:

    err! Unrecognized cursor_select_by strat 'bol'

I both cases, couldn't the anchor just start at the column `0` or is there good reason for why we're seeing this behavior?

**Comment by adsr** [comment]
Thanks!
