### ISSUE TITLE
Problem building on macOS

### ISSUE THREAD

**Issue by Tentro** [adsr/mle#38]
Whenever I clone the repository via `git clone --recursive https://github.com/adsr/mle` and build it with `make mle_vendor=1 mle_static=1` and without `mle_static=1` included it fails with two different errors. The former error with `mle_static=1` enabled throws me this: `ld: library not found for -lcrt0.o` and with the latter: https://pastebin.com/hCfXd0qQ 
am I missing something? I use mle on Linux and would like to use it on macOS as well.

**Comment by adsr** [comment]
Hi @Tentro thanks for the report. I wish I had a Mac so I could help debug.

It seems the linker is refusing to include the compiled dependencies:

> ld: warning: ignoring file vendor/termbox/src/libtermbox.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64

The error message does not make sense to me.

I believe @KevinSjoberg has used mle on macOS. He may have some tips.

**Comment by KevinSjoberg** [comment]
@Tentro @adsr this is what I do to build the binary on macOS:

1. `brew install libtool automake`
2. `git clone --recursive https://github.com/adsr/mle.git`
3. `make mle_vendor=1`
4. `make install prefix=$HOME` (I want my binary inside $HOME/bin)

**Comment by adsr** [comment]
@Tentro let us know if @KevinSjoberg 's method works for you.

**Comment by adsr** [comment]
@Tentro please reopen if you are still having trouble. Thanks.
