### ISSUE TITLE
Word motions fail on characters such as "å", "ä", "ö".

### ISSUE THREAD

**Issue by kevinsjoberg** [adsr/mle#42]
For instance, If I press `M-d` while standing on `hello`, the word is deleted. If I press `M-d` while standing on `företag`, only `f` is deleted, leaving me with `öretag`. Pressing `M-d` one more time completely removes the word.

This seem to be the case when anchoring and moving by word as well.

**Comment by adsr** [comment]
Good find!

The built-in regexes that determine word-forward and word-back behavior are `MLE_RE_WORD_FORWARD` and `MLE_RE_WORD_BACK` respectively. Both use `\w` and `\W` to match "word" and non-"word" characters. What counts as a "word" character appears to be determined by locale (env) and the flags `PCRE_UCP` and `PCRE_UTF*` which are available when PCRE is built  with `--enable-utf`. I scanned the docs and it sounds like when you use these flags, the subject string is required to be a valid UTF-8 string, so we'd need to make this some sort of runtime option. I tried playing around with it for a few minutes but could not get it to work straight away. Ideally we can figure out a way to support this with a runtime flag.

**Comment by kevinsjoberg** [comment]
@adsr did you ever come up with a solution for this?

**Comment by adsr** [comment]
I will take another look this weekend @kevinsjoberg

**Comment by adsr** [comment]
OK I figured it out. pcre must be compiled with both `--enable-utf` and `--enable-unicode-properties` to get this working. At runtime, the regex must also be compiled with `PCRE_UTF8` and `PCRE_UCP` flags. I have a working demo at https://github.com/adsr/pcre-utf-test

We should be able to make this a runtime option.

**Comment by adsr** [comment]
Have a look at https://github.com/adsr/mle/pull/53 @kevinsjoberg

**Comment by kevinsjoberg** [comment]
@adsr thank you so much! I'll try this out today. Sorry, for the long response time on my part. Really appreciate the follow up. 🙂

**Comment by adsr** [comment]
Closing some stale tickets. Feel free to reopen if anyone wants this feature.
