### ISSUE TITLE
How do I make my own syntax have precedence over syn_generic?

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#44]
I've setup my own syntax for Ruby. But whenever I open a Ruby file, `syn_generic` kicks in and I have to do `M-o y`, `syn_ruby` to switch the syntax to what I want. Both syntaxes are matching Ruby files.

I found this in the source

https://github.com/adsr/mle/blob/eb37d13ec10a997903bde375e85f6e8295ba0f53/bview.c#L628-L635

I guess since `syn_generic` is registered first and is matching Ruby files as well, it will always be chosen over any customisations. Is that right?

**Comment by adsr** [comment]
Ah yes, good catch! Let's see if we can iterate in reverse so that later syntaxes take priority.

**Comment by adsr** [comment]
Let me know how that works for you @KevinSjoberg. Thanks again.
