### ISSUE TITLE
Is it possible to use bright colors variants in syntax definitions?

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#45]
The documentation show that you can set black, red, yellow, blue, magenta, cyan, white as well as bold, underline and reverse. Is it possible to combine these, e.g, bold blue?

**Comment by adsr** [comment]
Yes, you can bitwise-or the flags.

```
    fg,bg        0=default     1=black       2=red         3=green
                 4=yellow      5=blue        6=magenta     7=cyan
                 8=white       256=bold      512=underline 1024=reverse
```

Bold and blue would be 256 + 5 = 261. Demo:

```
echo -en 'normal_blue\nbold_blue\n' | mle -N -S 'syn_test,.*,4,0' -s 'normal_blue,,5,0' -s 'bold_blue,,261,0' -y syn_test -H0
```

**Comment by KevinSjoberg** [comment]
Sweet, I'll probably add that to the man page then. 🙂
