### ISSUE TITLE
Nothing visible over serial connection (OpenWrt, Mipsel24kc)

### ISSUE THREAD

**Issue by detly** [adsr/mle#48]
Thanks for mle! Packing this much functionality into a 250kb editor means my colleagues can use something with post-1995 keybindings to help debug our embedded systems.

I've compiled this for OpenWrt on a MT7628 which is `mipsel_24kc` in most toolchains' terminology. It runs perfectly over SSH. However, if I try to run it over a serial line, no visible characters are printed to the screen.

Some specifics:

I'm using mle 1.4.3. Compiler is GCC 9.3 on an Ubuntu 20.04 host. It's cross compiling to `mipsel-openwrt-linux-musl` using the musl stdlib. When I launch mle (as either root or non-root user) via SSH, I see the usual default interface ie. line numbers down the left, status bar at the bottom, etc. When I launch mle over a serial connection (only as a root user), the screen is cleared and nothing further appears.

I've tried changing the `TERM` environment variable (`vt102`, `ansi`, `linux`, and `xterm-256color`) in the shell running mle and the shell running the serial console, and neither have any effect. I've used tio and minicom as a serial console, no difference.

I used tio to display the hex values of the data it captured. It seems to get about 50-60 bytes and then nothing else appears. You can see it below: the first few bytes are me typing `mle` and hitting enter (which I've annotated), and then mle's output follows.

```plain
6d 6c 65 0d 0a
 m  l  e enter ^--

03 07 03 07 1b 5b 3f 32 35 6c 1b 5b 3f 31 63 1b 5b 6d 0f 1b 5b 48
1b 5b 4a 1b 5b 3f 31 30 30 36 6c 1b 5b 3f 31 30 31 35 6c 1b 5b 3f
31 30 30 32 6c 1b 5b 3f 31 30 30 30 6c 
```

I wonder: is mle (or maybe termbox) waiting for something from the terminal that never happens in a serial connection?

Let me know if you think of any more info that would help.

**Comment by adsr** [comment]
Hey @detly rad! Yes I would imagine the ioctls and SIGWINCH handlers in termbox for determining screen size would not work over a serial console. I will try to reproduce in Virtualbox and get back to you.

**Comment by adsr** [comment]
I was able to reproduce over a virtual serial port between Virtualbox and minicom. Can you apply this patch to termbox and try again? https://gist.github.com/adsr/1d514ff07fa954e1564b6bb69ced7d1f It should fallback to an 80x24 screen.

**Comment by detly** [comment]
I'll try it out and let you know.

I also found out that there's a utility called "resize" which is nominally part of X11 but is available on most systems separately now. It works by setting the cursor position to some ridiculously big number and then checking where it was clamped to. This is available on OpenWrt and, in theory, works for serial terminals too. That might be a reasonable fallback in between checking `TIOCGWINSZ` and assuming 24x80, if you can be bothered calling out to it.

Alternatively it can be implemented from scratch based on this [Unix SE answer](https://unix.stackexchange.com/a/283206/11908).

**Comment by detly** [comment]
What version of Termbox is that patch against?

**Comment by detly** [comment]
Never mind, I found the appropriate lines. Unfortunately it didn't work. **However** if I run `eval $(resize)` first, it does. I'll leave it up to you whether you want to bake this into mle, or whether it's a bug in termbox (and I'll report it there), or whether systems making heavy use of UART need to do this in their packaging.

**Comment by adsr** [comment]
Interesting, yeah I'd like to fix it in termbox. Feel free to add more info here https://github.com/termbox/termbox/issues/7. Steps to setup a repro environment would be excellent.

**Comment by adsr** [comment]
Tracking here https://github.com/termbox/termbox/issues/9
