### ISSUE TITLE
File specified on the command line is not opened

### ISSUE THREAD

**Issue by detly** [adsr/mle#49]
I am running mle on an OpenWrt system targeting a MT7628 device. I haven't needed to do anything fancy to build it, the bundled makefile works fine with OpenWrt's buildroot.

When I start mle with eg. `mle /etc/config/umdns` (a regular file that I have read/write access to), mle actually starts with a blank buffer instead of the contents of `/etc/config/umdns`. The title of the buffer is `<buffer-0x931cd0>` suggesting that it just created a new one. I am running this all as `root`.

Opening the file with <kbd>Ctrl</kbd>+<kbd>o</kbd> works just fine, I can view, edit and save the file.

**Comment by detly** [comment]
I should point out that OpenWrt builds against musl not glibc. It also looks like `mle -h` doesn't show the help text, suggesting that it's not even getting the command line options.

**Comment by detly** [comment]
Well I feel a bit foolish. I created a wrapper script for mle to resolve the "terminal size over serial" issue, and totally forgot about it. My wrapper script did not pass arguments through to the mle binary. Now it does.

**Comment by adsr** [comment]
Hi @detly I'm curious what flags you use for resolving the terminal-size-over-serial issue. Thanks.

**Comment by detly** [comment]
> Hi @detly I'm curious what flags/env you use for resolving the terminal-size-over-serial issue. Thanks.

It's pretty simple, and I plan to submit the packaging to OpenWrt later unless you object. Basically:

1. I make the package depend on the "resize" features of Busybox ie. I list `+@BUSYBOX_CONFIG_RESIZE +@BUSYBOX_CONFIG_FEATURE_RESIZE_PRINT` as dependencies (as well as the other libs etc).
2. I configure the package to install the mle executable as `/usr/bin/mle-bin` instead of `/usr/bin/mle`.
3. I have a wrapper script that contains:

```sh
#!/bin/sh
eval "$(resize)"
mle-bin "$@"
```

This is installed as `/usr/bin/mle`.

The `resize` command is a Busybox util that does some cursor positioning tricks to determine the real size of the terminal, even over a serial link, and prints the appropriate environment variables. It's designed so you can `eval` the output in a shell to just set them:

```plain
# resize
COLUMNS=94;LINES=43;export COLUMNS LINES;
```

`resize` is available on non-OpenWrt systems too eg. on Debian and Ubuntu it's in the `xterm` package I think. (Technically it's also available as a standalone binary in OpenWrt.)

**Comment by detly** [comment]
(Theoretically I think you could just crib the resize code and put it in termbox if you wanted?)

**Comment by adsr** [comment]
I didn't realize until now you're the person from https://github.com/adsr/mle/issues/48! I'm glad you figured out a work-around.

Yes it's on my backlog to improve termbox. I began maintaining it a few months ago. First order of business is setting up some sort of CI to test features on various terms. Something like this would make a good test case.

**Comment by detly** [comment]
> I didn't realize until now you're the person from #48! 

:detective: 

> Yes it's on my backlog to improve termbox.

I definitely wouldn't fault you if you didn't want to include this in termbox, it's debatable whether it's within scope of the library or the user. Certainly it would make termbox more useful when such a workaround is necessary, but it's probably a rare edge case. Your call, of course.
