### ISSUE TITLE
Inspiration from dte

### ISSUE THREAD

**Issue by kevinsjoberg** [adsr/mle#56]
I've been playing around with [dte](https://craigbarnes.gitlab.io/dte) for a while now, and really enjoy large parts of its architecture. While I still use `mle` as my daily driver, I really miss some features that `dte` provides that `mle` doesn't.

- [run](https://craigbarnes.gitlab.io/dte/dterc.html#run). This allow me to shell out to an arbitrary command, do some work, and then end up in `dte` again. For example, I use this extensively with [tig](https://jonas.github.io/tig/). In fact, I found [External commands](https://craigbarnes.gitlab.io/dte/dterc.html#external-commands) to be a really powerful concept in general.
- [compile](https://craigbarnes.gitlab.io/dte/dterc.html#compile). This allows me to run compilers, build systems, code search utilities, etc. and then jump to a file/line position for each message.

What do you think @adsr, is there something in here worth pursuing? Perhaps much of this is already possible using the scripting API? If so, I'd love to discuss this in more detail. 🙂

**Comment by adsr** [comment]
Nice, I will check out dte and those commands and get back to you.

I prefer writing features in C if they are broadly useful / not too custom. Sometimes I feel like deleting the Lua API.

**Comment by kevinsjoberg** [comment]
Sounds good! 👍

**Comment by adsr** [comment]
Tried out dte today. I like the `errorfmt`/`compile` pattern as well and agree it would be a useful feature. It's general enough to apply to other tasks like syntax checking which has been in my scratch [todo list](https://github.com/adsr/mle/blob/1a62d3a35a1d7ddeeae1fc9670c76c563e007b80/mle.h#L689) for a while.

dte's `filter`, `pipe-*`, `run` are roughly achievable by `cmd_shell` and `cmd_suspend` I think. Is there a gap?

**Comment by hovsater** [comment]
> errorfmt/compile pattern as well and agree it would be a useful feature. It's general enough to apply to other tasks like syntax checking which has been in my scratch [todo list](https://github.com/adsr/mle/blob/1a62d3a35a1d7ddeeae1fc9670c76c563e007b80/mle.h#L689) for a while.

Yeah, `errorfmt` and `compile` are nice generic constructs. I use them for compiler errors, linting, type checking using ([typos](https://github.com/crate-ci/typos)) and many other things. It's really useful.

> dte's filter, pipe-*, run are roughly achievable by cmd_shell and cmd_suspend I think. Is there a gap?

The `filter` and `pipe-*` commands are akin to `cmd_shell`. But perhaps it makes sense to talk about the general construct, [exec](https://craigbarnes.gitlab.io/dte/dterc.html#exec), which all those commands are built upon. In fact, `filter`, `pipe-from` and `pipe-to` are all command aliases for an `exec` invocation.

```
alias filter 'exec -s -i buffer -o buffer -e errmsg'
alias pipe-from 'exec -s -o buffer -e errmsg'
alias pipe-to 'exec -s -i buffer -e errmsg'
alias run exec
```

What `exec` allows you to do is specify an input action and an output action for the command you're executing and the program may or may not be interactive. If it's interactive, dte suspends when the program runs until you exit it. If it's not interactive, dte executes the program synchronously without it taking over the terminal. It's a really powerful construct.

Here's a couple of use cases I'm using it for:

```
alias git-open 'exec -o open sh -c "git ls-files $(git rev-parse --show-cdup) | fzf -m --reverse"'
alias tig 'exec tig'
```

The first one, defines a command that allows me to run `git-open` and it will spawn `fzf` on the output of `git ls-files`. The output from `fzf` will then be opened in dte as the output action is set to `open`.

The second one just defines a command `tig`. Which allows me to do things like `tig blame $RFILE +$LINENO` to blame the current line in a file using `tig`. Here, `$RFILE` is a dte variable that expands to the relative path of the current file and `$LINENO` to the current line number.

**Comment by adsr** [comment]
Agree. I like how reusable and composable dte's`exec` is. If I had to begin mle again I would redesign how commands work (among other things). Presently commands can be passed a `static_param` (that you can specify as part of a key-binding). It's used in a few places but it's limiting. Good idea for mle v2.

**Comment by pepe** [comment]
And Janet programming language instead of Lua 😄
