### ISSUE TITLE
Access to wildcard params in lua 

### ISSUE THREAD

**Issue by NuclearKev** [adsr/mle#64]
Is there any way to get the wildcard params from the `ctx` in the `editor_register_cmd` callback?

**Comment by adsr** [comment]
Yes, this patch should get you started: https://gist.github.com/adsr/100c6ce4a9133033e227e6a7b84c5f28

As I've mentioned elsewhere, I'm leaning toward removing Lua support in the next release. I encourage feedback on the subject if you have any.

**Comment by NuclearKev** [comment]
I personally like having the ability to make extensions with lua. Although I haven't done much, I wrote a little extension to remove trailing whitespace when you save a buffer. It also gives the opportunity to create other fun things like maybe even some git extension similar to emacs' `magit`. That's just my take on it! :) 

Why were you considering removing?

**Comment by adsr** [comment]
Thanks, I appreciate the feedback. My personal thought is that it's a lot of code for a small benefit. The editor is easy to compile from source and modify, so I'd encourage power users to do that.

On the other hand, several people have now provided favorable feedback of the Lua plugin system, so maybe we'll keep it, maybe as a compile-time option.

I've been tossing around the idea of a libdl-based plugin system. The main advantage is that it wouldn't require any glue code, so issues like this one would not exist.

**Comment by NuclearKev** [comment]
Ah yes, I see what you mean. It wouldn't have been that much more difficult to do the things I've done in lua in C thanks to how well-written the project is. I would be interested to see a dynamically linked plugin system and see how it goes. I support either decision you make!
