### ISSUE TITLE
Can't remap C-space or C-/

### ISSUE THREAD

**Issue by NuclearKev** [adsr/mle#65]
I've remapped C-space in my `.mlerc` but it doesn't remap. In the mode bar (or whatever the bottom bar is called) I get a little n in the first slot, i.e. `mle_as[n...]`. C-/ does also not remap for some reason. Could this be a mac specific issue since I know there are default bindings that use C-/.

**Comment by adsr** [comment]
Good catch. This patch should make `C-space` mappable:

https://gist.github.com/adsr/9bbb3d2d50d50b2aec32adc7af665d5a

Feel free to submit that as a PR. Looks like `C-~` and `C-2` are equivalent to `C-space`.

`C-/` works on my setup so there might be something else intercepting the input. You can try strace'ing mle to see if the terminal emulator is forwarding the input:

```
adam@asx1c9:~$ strace -p $(pgrep mle) -e trace=read
strace: Process 5083 attached
...
(input C-/ on mle)
...
read(3, "\37", 64)                      = 1
```

**Comment by NuclearKev** [comment]
Sweet! That fix worked. Made the PR #66 with your fix. Also, you are correct about the terminal emulator being weird. I've been using mle on my work computer (a Mac) and the standard terminal emulator doesn't like C-/. Thanks!
