### ISSUE TITLE
Copied text doesn't copy across buffers

### ISSUE THREAD

**Issue by NuclearKev** [adsr/mle#67]
This seems to be intermittent but once it happens in a session it'll always happen. If I copy a piece of text in buffer A and attempt to paste it into buffer B it just pastes the last thing copied/cut in buffer B rather than what was copied from buffer A. This could have been done on purpose but it seems like a bug to me. Correct me if I'm wrong!

EDIT: I am not using the system clipboard.

**Comment by adsr** [comment]
Hi @NuclearKev. Yes the behavior you're describing is defined here:

https://github.com/adsr/mle/blob/0185bd15cec74d5b11f9e630dbf2ec20c38a9dd6/cursor.c#L252

Each cursor has its own cut-buffer (clipboard), which enables some useful multi-cursor operations. There's also an editor-wide cut-buffer that holds the last cut of any cursor. When uncutting (pasting), if the cursor cut-buffer is empty, it tries the editor-wide one.

I have also been annoyed by this when trying to copy across buffers. In b43575af6df0a647d5912dbdb8d6d0e88ce25d3d I added a command `cmd_uncut_last` to specifically get at the global cut-buffer, mapped to `CM-u` by default. (I was going to map to `CS-u` but that's the default key binding for IBus Unicode input.)
