### ISSUE TITLE
suggestion on debian packaging

### ISSUE THREAD

**Issue by cdluminate** [adsr/mle#69]
After releasing v1.5.0, please only modify files in the debian/ directory. Because I will use `uscan` to download v1.5.0 tarball. In this case, the modified `debian.sh` outside of debian/ directory will cause a small problem for me to build the package because files outside debian/ directory has been changed since v1.5.0 tag. As a result, I'm uploading the 5e7828aae0a9e2c2af1f05e74286c679d38ef8cf snapshot to Debian as the 1.5.0 release.

By the way, I live on github. The next time you want sponsorship you may directory AT me and assign the issue to me.

**Comment by cdluminate** [comment]
I have uploaded `mle_1.5.0-1_source.changes` to debian unstable.

**Comment by adsr** [comment]
Thanks @cdluminate. I'll tag you next time I cut a release.

**Comment by adsr** [comment]
Hi @cdluminate I will release 1.6.0 soon. I was going to make a new `debian_1_6_0` branch off the v1.6.0 commit and then add in the updated `debian/` folder. But after reading your comment again I'm not sure that is convenient for you. Do you have any tips or recommendations?

**Comment by cdluminate** [comment]
A `debian_1_6_0` branch is ok. Remind that the core issue is that any file outside of the `debian` directory must not be changed with respect to the latest source version documented in `debian/changelog`. For instance, if the first entry of `debian/changelog` is version A, then the source tree outside of the debian directory have to be identical to the upstream release A, or it will simply fail to build due to source code mismatch. If the top entry of `debian/changelog` is version B, then the source tree outside `debian` directory must match the version B that can be downloaded from the github release page.

As long as we follow this and avoid triggering build failures, whatever branch name or workflow will do.

**Comment by cdluminate** [comment]
BTW, debian is currently in the deep freeze stage. Major updates are generally not recommended in this period because we don't know how much new bug is hidden in the new release.

That said, you still have the option to upload 1.6.0 to catch up with our next stable release. You can evaluate the upgrade risk better than me.

**Comment by adsr** [comment]
Thank you @cdluminate. I think I understand now. Basically it was a problem because https://github.com/adsr/mle/compare/v1.5.0...debian_1_5_0 contained changes outside of the `debian/` directory (`debian.sh`). I can avoid that in the next release.

This would be a patch release if not for the upgrade from PCRE to PCRE2. I think that warrants a minor version bump. I have no rush to get this version into the new Debian release. It's fine by me to leave it in experimental or unstable for now.

**Comment by adsr** [comment]
@cdluminate  I made a `debian_1_7_2` branch, this time without the `debian.sh`  script that caused a problem last time. I also uploaded the package.

```
Uploading to ftp-master (via ftp to ftp.upload.debian.org):
  Uploading mle_1.7.2-1.dsc: done.
  Uploading mle_1.7.2.orig.tar.xz: done.
  Uploading mle_1.7.2-1.debian.tar.xz: done.
  Uploading mle_1.7.2-1_source.buildinfo: done.
  Uploading mle_1.7.2-1_source.changes: done.
Successfully uploaded packages.

```
