### ISSUE TITLE
Fix UTF-8 rendering

### ISSUE THREAD

**Issue by pepa65** [adsr/mle#7]
Cool editor! It would be great if UTF-8 could be handled well. If you look at [UTF-8 demo](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt) the Thai text isn't working well in `mle`.

**Comment by adsr** [comment]
Hello, thanks for checking out the editor. mle has full multibyte support. The Thai chars look ok on my end[0]. You may need to adjust locale env vars and/or terminal emulator settings. Feel free to reopen if there is another issue I'm missing.

[0] http://i.imgur.com/6PBFNUR.png

**Comment by pepa65** [comment]
It does look fine on your end, Maybe you can include instructions for packagers? On standard Ubuntu 20.04 LTS it is still very broken...

**Comment by adsr** [comment]
Hi @pepa65, I will try building on 20.04 and get back to you on that.

Regarding the multibyte issue, I think this will fix:

https://gist.github.com/adsr/59ba1b6642b8ae8f24a3f5b3d4ccb934

I'll merge after writing a test. Thanks for the report!

**Comment by adsr** [comment]
Improved with 75136ae but need to address https://github.com/termbox/termbox/issues/1 to fix properly
