### ISSUE TITLE
TUI hangs indefinitely on macOS

### ISSUE THREAD

**Issue by alebcay** [adsr/mle#71]
Hello, I found that building `mle` on macOS 12.4 (Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64) succeeds, but when trying to run it interactively, the editor does not accept any input and none of the keyboard shortcuts work either.

It turns out that [this is an issue in `termbox2`](https://github.com/termbox/termbox2/issues/31) which has [been fixed](https://github.com/termbox/termbox2/pull/33). Would it be possible to update to a newer version of `termbox2` in this project to pick up the fix?

In the meantime, macOS users can add `-DTB_OPT_SELECT` to `CFLAGS` before building to work around this, but it would be great if this workaround could be skipped (seeing as the need for this flag on macOS is not very well documented either here or upstream in `termbox2`).

**Comment by adsr** [comment]
Thanks for the reminder. Updated termbox in a247c9c8dd1adb3e9fdb4e4f32f30ba5413df664.
