### ISSUE TITLE
LSP support

### ISSUE THREAD

**Issue by R1yuu** [adsr/mle#72]
I think this editor would benefit massively if the Language Server Protocol was implemented to make it more viable for coding.

**Comment by adsr** [comment]
Hello, thanks for the feedback. This would be better off implemented as a user script rather than a built-in feature. If you or anyone else pursues this, please keep us posted.

**Comment by kevinsjoberg** [comment]
I'm actually thinking of pursuing this given the amount of time I spend in mle on a daily basis. 🙂 Any pointers, @adsr?

**Comment by R1yuu** [comment]
> I'm actually thinking of pursuing this given the amount of time I spend in mle on a daily basis. slightly_smiling_face Any pointers, @adsr?

You could look at the implementation of the LSP extension for the micro text editor: https://github.com/AndCake/micro-plugin-lsp

**Comment by adsr** [comment]
That would be epic. I predict you will find shortcomings in the plugin API. Feel free to submit PRs or issues for any of that.

**Comment by adsr** [comment]
Feel free to re-open if there is any progress.
