### ISSUE TITLE
Where is config file

### ISSUE THREAD

**Issue by glow12121** [adsr/mle#75]
A newbie questions. Just installed mle on Arch. Where is the config file?

**Update** I have read `mle -h` and `man mle` carefully but there's no info as to where to look for a full list of possible keybindings.

I have found out that there's already soft-wrapping implemented, which is great, but is there an option to soft-wrap text at a given character number?

Also, is there a mle discussion group, as I hate to be spamming the issue tracker with questions?

**Comment by adsr** [comment]
Hi, apologies for the delayed response.

> Update I have read mle -h and man mle carefully but there's no info as to where to look for a full list of possible keybindings.

You're right that'd make a good addition to the help file. For now you can look at the strings in `keys.h` in the source tree. You can optionally prefix any of those with `C-` (ctrl), `M-` (alt/meta), `S-` (shift), or a combination of those. Note not all combinations make sense.

> I have found out that there's already soft-wrapping implemented, which is great, but is there an option to soft-wrap text at a given character number?

There isn't but that would be easy to add. I think what we really want is a full soft-wrap implementation. The current implementation is per-line only, which is clever, but it would be nice to have a full soft-wrap mode with ability to set a max line width. I'll make a separate issue for this.

> Also, is there a mle discussion group, as I hate to be spamming the issue tracker with questions?

There isn't to my knowledge. Feel free to continue posting questions here.

**Comment by adsr** [comment]
> You're right that'd make a good addition to the help file. For now you can look at the strings in keys.h in the source tree. You can optionally prefix any of those with C- (ctrl), M- (alt/meta), S- (shift), or a combination of those. Note not all combinations make sense.

I forgot that I documented this already in the "KEY NAMES" section of the manpage. `mle -Qk` is particularly helpful.
