### ISSUE TITLE
Alt (option) on Mac not working

### ISSUE THREAD

**Issue by allestaire** [adsr/mle#81]
Tried to use this awesome tool for texteditor but seems like Alt  key wont response on Mac OS

https://github.com/adsr/mle/assets/68372409/259e5591-870a-4e7d-920e-a42c57a6ecbe

`mle version 1.7.2`

**Comment by allestaire** [comment]
I guess this are the only accepted commands on `alt - option (M)`

<img width="1544" alt="Screen Shot 2023-06-22 at 6 08 58 PM" src="https://github.com/adsr/mle/assets/68372409/24645ffc-bd1e-4ad4-a09e-cd86641d9216">

**Comment by allestaire** [comment]
Got a solution to the problem,

<img width="1440" alt="Screen Shot 2023-06-22 at 9 40 27 PM" src="https://github.com/adsr/mle/assets/68372409/bbc954d0-bc0d-4ca0-ae92-c7c18461426d">
<img width="1544" alt="Screen Shot 2023-06-22 at 9 41 24 PM" src="https://github.com/adsr/mle/assets/68372409/c7ae93b5-e8a7-4e46-affd-d19bd90dd69a">

**Comment by allestaire** [comment]
Seems like shifts are not totally supported

<img width="285" alt="Screen Shot 2023-06-22 at 10 08 44 PM" src="https://github.com/adsr/mle/assets/68372409/aa46b251-91b2-4e71-a46f-e6287b24ce9c">

**Comment by adsr** [comment]
Hello, I don't have mac to test with at the moment, however I know the default settings on the macOS Terminal app do not emit all the usual escape codes. You already found one fix ("Use Option as Meta key"). For modified directional keys, you might try adding mappings for the following:

https://github.com/adsr/mle/blob/6f514a4e55d4d7ac3bce901bd188d1047e8f48e2/termbox2.h#L994-L1025

(Note "\x1b" is the hex equivalent of octal "\033". You may need to use the octal form for it to work.)

**Comment by allestaire** [comment]
> Hello, I don't have mac to test with at the moment, however I know the default settings on the macOS Terminal app do not emit all the usual escape codes. You already found one fix ("Use Option as Meta key"). For modified directional keys, you might try adding mappings for the following:
> 
> https://github.com/adsr/mle/blob/6f514a4e55d4d7ac3bce901bd188d1047e8f48e2/termbox2.h#L994-L1025
> 
> (Note "\x1b" is the hex equivalent of octal "\033". You may need to use the octal form for it to work.)

Thanks for your response!! this helps me to test 😄
