### ISSUE TITLE
Awesome work! A question about cross compiling

### ISSUE THREAD

**Issue by bm16ton** [adsr/mle#82]
Thank you for am excellant project! Every so often (more then I like) I need to cross compile a small simple text editor to sum niche/corner case box, like a mips box running openwrt or sum arm running tizen etc.Boy this always ends up being more of a nightmare then it should. Obviously dependencies are an issue and can get out of control quick, not to mention all the "fixing" they may need to compile against whatever libs are avail. The other issue with say Nano, is it requires a lot more from the terminal then mle does. Its another common issue for nano/pico to compile but kick out early because of the heavy requirements it has for tty. But mle compiled and worked great this last go round (well Tizen 2.3.1 worked great 5.5 all seemed good but sorta just freezes when I try to save, ill look into that) I guess I'm just curious if you ever contemplate what direction to take this project in? My humble vote would be towards slimming as many depencies out as possible, maybe make the build a little more cross compile friendly (if I have time ill try a pull together a PR)  and keep the terminal reqs as low as possible. As it stands your way ahead of the rest for those of us who frequently hack embedded/hacked/weird systems (various vi versions not with standing, I never liked them but reqs are low as I understand it). Its always nice when a project can fill a niche the others haven't covered. I hope you find that interesting, if not its still an awesome project! Thank you good sir.

**Comment by adsr** [comment]
Thank you for the feedback!

> I guess I'm just curious if you ever contemplate what direction to take this project in? My humble vote would be towards slimming as many depencies out as possible

I'm aganist deps

**Comment by adsr** [comment]
Thank you for the feedback! Feel free to file any bugs you find on mips or arm. I don't have any non-intel machines at the moment, but I've been intending to get some toy non-intel PCs as this sort of thing seems to come up every now and then.

> I guess I'm just curious if you ever contemplate what direction to take this project in? My humble vote would be towards slimming as many depencies out as possible

Yes, I agree. I won't add any other dependencies and I've long contemplated removing the Lua dep. I don't personally use it but some users like the scripting feature so maybe I'll make it a compile-time option.

> maybe make the build a little more cross compile friendly (if I have time ill try a pull together a PR)

That would be excellent. Thank you.
