### ISSUE TITLE
Fix scan-build warnings

### ISSUE THREAD

**Issue by adsr** [adsr/mle#84]
Running clang's static analyzer `scan-build`:

```console
$ scan-build make clean_quick all mle_vendor=1
```
emits the following warnings:

![image](https://github.com/user-attachments/assets/5c46a28b-5837-47ba-912e-766f3e9f18e9)

I looked at a few and they appear to be simple fixes -- good for Hacktoberfest.

**Comment by proh14** [comment]
Hello :), I'm working on it!

#85
