### ISSUE TITLE
Is there an interest in a community channel?

### ISSUE THREAD

**Issue by hovsater** [adsr/mle#86]
Long time, no see, @adsr! How are you? 🙂 

I was wondering, if you would be interested in setting up a channel for mle on https://libera.chat/ or Discord? Totally fine, if you're not interested in doing that, but I thought I'd ask at least.

**Comment by adsr** [comment]
Ltns @hovsater! Hope you are well.

Sure, I registered #mle on libera. I'll idle in there.

**Comment by hovsater** [comment]
Btw, I'm still around in #mle if you ever decide to came back there! 😅
