### ISSUE TITLE
Git `COMMIT_EDITMSG` color

### ISSUE THREAD

**Issue by rentruewang** [adsr/mle#87]
I would like to request a feature where to color the output of git commit's edit messages.

For example, vscode would color the line deleted / new file / modified as different colors, and I'm hoping mle could do the same.

**Comment by adsr** [comment]
Hi @rentruewang, you can try adding the following to your `.mlerc`:

```
-Ssyn_git_commit_editmsg,(^|/)COMMIT_EDITMSG$,4,1
-s^#\s+deleted:.*$,2,0
-s^#\s+new file:.*$,3,0
-s^#\s+modified:.*$,4,0
```

(or, if you use an executable `.mlerc`, something to print this out)

It will look like this:

![image](https://github.com/user-attachments/assets/f2146b7a-9b1a-4bbf-8ca0-02eed471184d)

Feel free to re-open if you have any trouble.

**Comment by rentruewang** [comment]
@adsr Wow this is amazing! Is it possible to include this into the default distribution (like how mle does syntax highlight for popular languages). I believe it would be very useful for new users in the future :)

**Comment by adsr** [comment]
Yes, I'd like to add better built-in syntax rules. The current `syn_generic` syntax is a mix of rules for many languages. Some have requested proper syntax rules.

I'd also like to make a wiki for user-contributed syntax rules, key bindings, user scripts, etc.

**Comment by rentruewang** [comment]
Sounds great! Looking forward to it.
